import Footer from "./Components/Footer/Footer";
import Navbar from "./Components/Navbar/Navbar";
import { sora, trajan } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sora.variable} ${trajan.variable}`}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
